name: "Relano - Automated 'What's new' Videos"
description: "Create automated "
author: "Just-Moh-it"
branding:
  icon: zap
  color: green
inputs:
  openai-api-key: # change this
    required: true
    description: "API key for OpenAI"
  releaseNotes:
    required: true
    description: "Release notes for the new version"
  repositorySlug:
    required: true
    description: "Repository slug (eg: remotion-dev/remotion)"
  releaseTag:
    required: true
    description: "Release tag (eg: v3.4.4)"
runs:
  using: "node16"
  main: "dist/index.js"
